# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dom/projects/pace/paralell/cstar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dom/projects/pace/paralell/cstar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dom/projects/pace/paralell/cstar/CMakeFiles /home/dom/projects/pace/paralell/cstar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dom/projects/pace/paralell/cstar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cstar

# Build rule for target.
cstar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cstar
.PHONY : cstar

# fast build rule for target.
cstar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/build
.PHONY : cstar/fast

block.o: block.cpp.o
.PHONY : block.o

# target to build an object file
block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/block.cpp.o
.PHONY : block.cpp.o

block.i: block.cpp.i
.PHONY : block.i

# target to preprocess a source file
block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/block.cpp.i
.PHONY : block.cpp.i

block.s: block.cpp.s
.PHONY : block.s

# target to generate assembly for a file
block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/block.cpp.s
.PHONY : block.cpp.s

displays.o: displays.cpp.o
.PHONY : displays.o

# target to build an object file
displays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/displays.cpp.o
.PHONY : displays.cpp.o

displays.i: displays.cpp.i
.PHONY : displays.i

# target to preprocess a source file
displays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/displays.cpp.i
.PHONY : displays.cpp.i

displays.s: displays.cpp.s
.PHONY : displays.s

# target to generate assembly for a file
displays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/displays.cpp.s
.PHONY : displays.cpp.s

errors.o: errors.cpp.o
.PHONY : errors.o

# target to build an object file
errors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/errors.cpp.o
.PHONY : errors.cpp.o

errors.i: errors.cpp.i
.PHONY : errors.i

# target to preprocess a source file
errors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/errors.cpp.i
.PHONY : errors.cpp.i

errors.s: errors.cpp.s
.PHONY : errors.s

# target to generate assembly for a file
errors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/errors.cpp.s
.PHONY : errors.cpp.s

exec.o: exec.cpp.o
.PHONY : exec.o

# target to build an object file
exec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/exec.cpp.o
.PHONY : exec.cpp.o

exec.i: exec.cpp.i
.PHONY : exec.i

# target to preprocess a source file
exec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/exec.cpp.i
.PHONY : exec.cpp.i

exec.s: exec.cpp.s
.PHONY : exec.s

# target to generate assembly for a file
exec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/exec.cpp.s
.PHONY : exec.cpp.s

execlib.o: execlib.cpp.o
.PHONY : execlib.o

# target to build an object file
execlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/execlib.cpp.o
.PHONY : execlib.cpp.o

execlib.i: execlib.cpp.i
.PHONY : execlib.i

# target to preprocess a source file
execlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/execlib.cpp.i
.PHONY : execlib.cpp.i

execlib.s: execlib.cpp.s
.PHONY : execlib.s

# target to generate assembly for a file
execlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/execlib.cpp.s
.PHONY : execlib.cpp.s

expression.o: expression.cpp.o
.PHONY : expression.o

# target to build an object file
expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/expression.cpp.o
.PHONY : expression.cpp.o

expression.i: expression.cpp.i
.PHONY : expression.i

# target to preprocess a source file
expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/expression.cpp.i
.PHONY : expression.cpp.i

expression.s: expression.cpp.s
.PHONY : expression.s

# target to generate assembly for a file
expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/expression.cpp.s
.PHONY : expression.cpp.s

interpret.o: interpret.cpp.o
.PHONY : interpret.o

# target to build an object file
interpret.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/interpret.cpp.o
.PHONY : interpret.cpp.o

interpret.i: interpret.cpp.i
.PHONY : interpret.i

# target to preprocess a source file
interpret.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/interpret.cpp.i
.PHONY : interpret.cpp.i

interpret.s: interpret.cpp.s
.PHONY : interpret.s

# target to generate assembly for a file
interpret.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/interpret.cpp.s
.PHONY : interpret.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

program.o: program.cpp.o
.PHONY : program.o

# target to build an object file
program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/program.cpp.o
.PHONY : program.cpp.o

program.i: program.cpp.i
.PHONY : program.i

# target to preprocess a source file
program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/program.cpp.i
.PHONY : program.cpp.i

program.s: program.cpp.s
.PHONY : program.s

# target to generate assembly for a file
program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/program.cpp.s
.PHONY : program.cpp.s

statement.o: statement.cpp.o
.PHONY : statement.o

# target to build an object file
statement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/statement.cpp.o
.PHONY : statement.cpp.o

statement.i: statement.cpp.i
.PHONY : statement.i

# target to preprocess a source file
statement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/statement.cpp.i
.PHONY : statement.cpp.i

statement.s: statement.cpp.s
.PHONY : statement.s

# target to generate assembly for a file
statement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cstar.dir/build.make CMakeFiles/cstar.dir/statement.cpp.s
.PHONY : statement.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cstar"
	@echo "... block.o"
	@echo "... block.i"
	@echo "... block.s"
	@echo "... displays.o"
	@echo "... displays.i"
	@echo "... displays.s"
	@echo "... errors.o"
	@echo "... errors.i"
	@echo "... errors.s"
	@echo "... exec.o"
	@echo "... exec.i"
	@echo "... exec.s"
	@echo "... execlib.o"
	@echo "... execlib.i"
	@echo "... execlib.s"
	@echo "... expression.o"
	@echo "... expression.i"
	@echo "... expression.s"
	@echo "... interpret.o"
	@echo "... interpret.i"
	@echo "... interpret.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
	@echo "... statement.o"
	@echo "... statement.i"
	@echo "... statement.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

